# -*- coding: utf-8 -*-
data = {
    "bulk": [
        {
            "work": {
                "created-date": {
                    "value": 1454109749695
                },
                "last-modified-date": {
                    "value": 1454109749695
                },
                "source": {
                    "source-orcid": None,
                    "source-client-id": {
                        "uri": "http://sandbox.orcid.org/client/APP-P5ANJTQRRTMA6GXZ",
                        "path": "APP-P5ANJTQRRTMA6GXZ",
                        "host": "sandbox.orcid.org"
                    },
                    "source-name": {
                        "value": "NASA Astrophysics Data System"
                    }
                },
                "put-code": 513293,
                "path": None,
                "title": {
                    "title": {
                        "value": "Magnetic fields in spiral galaxies"
                    },
                    "subtitle": None,
                    "translated-title": None
                },
                "journal-title": None,
                "short-description": "Radio synchrotron emission, its polarization and Faraday rotation of the polarization angle are powerful tools to study the strength and structure of magnetic fields in galaxies. Unpolarized synchrotron emission traces isotropic turbulent fields which are strongest in spiral arms and bars (20-30 \\upmu G) and in central starburst regions (50-100 \\upmu G). Such fields are dynamically important; they affect gas flows and drive gas inflows in central regions. Polarized emission traces ordered fields, which can be regular or anisotropic turbulent, where the latter originates from isotropic turbulent fields by the action of compression or shear. The strongest ordered fields (10-15 \\upmu G) are generally found in interarm regions. In galaxies with strong density waves, ordered fields are also observed at the inner edges of spiral arms. Ordered fields with spiral patterns exist in grand-design, barred and flocculent galaxies and in central regions. Ordered fields in interacting galaxies have asymmetric distributions and are a tracer of past interactions between galaxies or with the intergalactic medium.—Faraday rotation measures of the diffuse polarized radio emission from galaxy disks reveal large-scale spiral patterns that can be described by the superposition of azimuthal modes; these are signatures of regular fields generated by mean-field dynamos. \"Magnetic arms\" between gaseous spiral arms may also be products of dynamo action, but need a stable spiral pattern to develop. Helically twisted field loops winding around spiral arms were found in two galaxies so far. Large-scale field reversals, like the one found in the Milky Way, could not yet be detected in external galaxies. In radio halos around edge-on galaxies, ordered magnetic fields with X-shaped patterns are observed. The origin and evolution of cosmic magnetic fields, in particular their first occurrence in young galaxies and their dynamical importance during galaxy evolution, will be studied with forthcoming radio telescopes like the Square Kilometre Array.",
                "citation": None,
                "type": "JOURNAL_ARTICLE",
                "publication-date": {
                    "year": {
                        "value": "2016"
                    },
                    "month": {
                        "value": "12"
                    },
                    "day": None,
                    "media-type": None
                },
                "external-ids": {
                    "external-id": [
                        {
                            "external-id-type": "bibcode",
                            "external-id-value": "2016A&ARv..24....4B",
                            "external-id-url": None,
                            "external-id-relationship": "SELF"
                        },
                        {
                            "external-id-type": "other-id",
                            "external-id-value": "11266367",
                            "external-id-url": None,
                            "external-id-relationship": "SELF"
                        },
                        {
                            "external-id-type": "doi",
                            "external-id-value": "10.1007/s00159-015-0084-4",
                            "external-id-url": None,
                            "external-id-relationship": "SELF"
                        }
                    ]
                },
                "url": {
                    "value": "https://ui.adsabs.harvard.edu/#abs/2016A&ARv..24....4B"
                },
                "contributors": {
                    "contributor": [
                        {
                            "contributor-orcid": None,
                            "credit-name": {
                                "value": "Beck, Rainer"
                            },
                            "contributor-email": None,
                            "contributor-attributes": {
                                "contributor-sequence": None,
                                "contributor-role": "AUTHOR"
                            }
                        }
                    ]
                },
                "language-code": None,
                "country": None,
                "visibility": "PUBLIC"
            }
        },
        {
            "work": {
                "created-date": {
                    "value": 1454345216962
                },
                "last-modified-date": {
                    "value": 1454345216962
                },
                "source": {
                    "source-orcid": None,
                    "source-client-id": {
                        "uri": "http://sandbox.orcid.org/client/APP-P5ANJTQRRTMA6GXZ",
                        "path": "APP-P5ANJTQRRTMA6GXZ",
                        "host": "sandbox.orcid.org"
                    },
                    "source-name": {
                        "value": "NASA Astrophysics Data System"
                    }
                },
                "put-code": 513305,
                "path": None,
                "title": {
                    "title": {
                        "value": "<SUP>40</SUP>Ar/<SUP>39</SUP>Ar and cosmic ray exposure ages of plagioclase-rich lithic fragments from Apollo 17 regolith, 78461"
                    },
                    "subtitle": None,
                    "translated-title": None
                },
                "journal-title": None,
                "short-description": "Argon isotopic data is used to assess the potential of low-mass samples collected by sample return missions on planetary objects (e.g., Moon, Mars, asteroids), to reveal planetary surface processes. We report the first <SUP>40</SUP>Ar/<SUP>39</SUP>Ar ages and <SUP>38</SUP>Ar cosmic ray exposure (CRE) ages, determined for eleven submillimeter-sized (ranging from 0.06 to 1.2 mg) plagioclase-rich lithic fragments from Apollo 17 regolith sample 78461 collected at the base of the Sculptured Hills. Total fusion analysis was used to outgas argon from the lithic fragments. Three different approaches were used to determine <SUP>40</SUP>Ar/<SUP>39</SUP>Ar ages and illustrate the sensitivity of age determination to the choice of trapped (<SUP>40</SUP>Ar/<SUP>36</SUP>Ar)<SUB>t</SUB>. <SUP>40</SUP>Ar/<SUP>39</SUP>Ar ages range from ~4.0 to 4.4 Ga with one exception (Plag#10). Surface CRE ages, based on <SUP>38</SUP>Ar, range from ~1 to 24 Ma. The relatively young CRE ages suggest recent re-working of the upper few centimeters of the regolith. The CRE ages may result from the effect of downslope movement of materials to the base of the Sculptured Hills from higher elevations. The apparent <SUP>40</SUP>Ar/<SUP>39</SUP>Ar age for Plag#10 is 〉5 Ga and yielded the oldest CRE age (i.e., ~24 Ma). We interpret this data to indicate the presence of parentless <SUP>40</SUP>Ar in Plag#10, originating in the lunar atmosphere and implanted in lunar regolith by solar wind. Based on a chemical mixing model, plagioclase compositions, and <SUP>40</SUP>Ar/<SUP>39</SUP>Ar ages, we conclude that lithic fragments originated from Mg-suite of highland rocks, and none were derived from the mare region.",
                "citation": None,
                "type": "JOURNAL_ARTICLE",
                "publication-date": {
                    "year": {
                        "value": "2016"
                    },
                    "month": {
                        "value": "12"
                    },
                    "day": None,
                    "media-type": None
                },
                "external-ids": {
                    "external-id": [
                        {
                            "external-id-type": "bibcode",
                            "external-id-value": "2016EP&S...68...11D",
                            "external-id-url": None,
                            "external-id-relationship": "SELF"
                        },
                        {
                            "external-id-type": "other-id",
                            "external-id-value": "11311823",
                            "external-id-url": None,
                            "external-id-relationship": "SELF"
                        },
                        {
                            "external-id-type": "doi",
                            "external-id-value": "10.1186/s40623-016-0381-9",
                            "external-id-url": None,
                            "external-id-relationship": "SELF"
                        }
                    ]
                },
                "url": {
                    "value": "https://ui.adsabs.harvard.edu/#abs/2016EP&S...68...11D"
                },
                "contributors": {
                    "contributor": [
                        {
                            "contributor-orcid": None,
                            "credit-name": {
                                "value": "Das, J. P."
                            },
                            "contributor-email": None,
                            "contributor-attributes": {
                                "contributor-sequence": None,
                                "contributor-role": "AUTHOR"
                            }
                        },
                        {
                            "contributor-orcid": None,
                            "credit-name": {
                                "value": "Baldwin, S. L."
                            },
                            "contributor-email": None,
                            "contributor-attributes": {
                                "contributor-sequence": None,
                                "contributor-role": "AUTHOR"
                            }
                        },
                        {
                            "contributor-orcid": None,
                            "credit-name": {
                                "value": "Delano, J. W."
                            },
                            "contributor-email": None,
                            "contributor-attributes": {
                                "contributor-sequence": None,
                                "contributor-role": "AUTHOR"
                            }
                        }
                    ]
                },
                "language-code": None,
                "country": None,
                "visibility": "PUBLIC"
            }
        }
    ]
}